packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@clickhouse/client': ^1.13.0
  '@dotenvx/dotenvx': ^1.51.1
  '@faker-js/faker': ^10.1.0
  '@types/pg': ^8.15.6
  dayjs: ^1.11.19
  pg: ^8.16.3
  pg-logical-replication: ^2.2.1

catalogs:
  cli:
    '@antfu/eslint-config': ^6.2.0
    '@antfu/ni': ^27.0.1
    bumpp: ^10.3.1
    eslint: ^9.39.1
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
    tsdown: ^0.16.0
    tsx: 4.20.6
    typescript: ^5.9.3
    vite: ^7.2.1
  inlined:
    '@antfu/utils': ^9.3.0
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.7
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.1
  types:
    '@types/node': ^24.10.0

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks

shellEmulator: true
