CREATE TABLE IF NOT EXISTS szfgjj_grjcmx_copy1 (
  xh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grzh VARCHAR(12) NOT NULL,
  jcdw VARCHAR(255),
  xingming VARCHAR(42) NOT NULL,
  zjhm VARCHAR(18),
  jcje NUMERIC(12, 2) NOT NULL,
  jzrq DATE NOT NULL,
  swap_data_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_szfgjj_zjhm UNIQUE (zjhm, grzh),
  CONSTRAINT chk_szfgjj_zjhm_length CHECK (LENGTH(zjhm) = 18)
);

COMMENT ON TABLE szfgjj_grjcmx_copy1 IS '个人缴存明细';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.xh IS '序号';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.grzh IS '个人账号';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.jcdw IS '缴存单位';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.xingming IS '姓名';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.zjhm IS '身份证';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.jcje IS '缴存金额';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.jzrq IS '记账日期';
COMMENT ON COLUMN szfgjj_grjcmx_copy1.swap_data_time IS '更新时间';

-- INSERT INTO szfgjj_grjcmx_copy1 (
--   grzh, jcdw, xingming, zjhm, jcje, jzrq, swap_data_time
-- ) VALUES
-- ('000414000002', '南充经发出租汽车有限公司', '张三', '511302197701266699', 2160.00, '2019-01-09', '2025-06-23 15:44:09'),
-- ('000414000003', '南充经发出租汽车有限公司', '李四', '512901197409129191', 2160.00, '2019-01-09', '2025-06-23 15:44:09'),
-- ('000414000004', '南充经发出租汽车有限公司', '王五', '512901197009262629', 2000.00, '2019-01-09', '2025-06-23 15:44:09');